### ISSUE TITLE
seeking is throwing error

### ISSUE THREAD

**Issue by iamabid** [nypublicradio/ember-hifi#33]
when ever i seek the audio, there is this error thrown by the browser in the console "DOMException: The play() request was interrupted by a call to pause().", this is causing pretty inconsistent behaviour to the audio player.

browser: chrome 57
os : osx

**Comment by noslouch** [comment]
Can you provide a twiddle with a reduced test case? What kind of inconsistent behavior are you seeing?

That error is thrown from chrome's internals. There was a recent change in version 50 that returns a promise from the play method. This isn't widely support though, and it our testing that error has been safely ignored.

The more likely cause of the problems you're seeing in seeking is due to the servers handling of the `Range` header, which chrome uses when requesting audio files. How are you serving your audio files? Using the ember express server?

**Comment by jkeen** [comment]
(Also, are you on the latest version of `ember-hifi`? )

**Comment by noslouch** [comment]
Let us know if you're still having trouble. This sounds like a problem with respecting the Range header though.
