### ISSUE TITLE
Firefox Quantum does not identify streams correctly

### ISSUE THREAD

**Issue by jkeen** [nypublicradio/ember-hifi#45]
Firefox Quantum has a similar problem Opera had with regard to stream duration, as can be reproduced here: https://jsfiddle.net/jkeen/3bx77t2u/2/

For Opera I put in [this hacky workaround](https://github.com/nypublicradio/ember-hifi/blob/master/addon/hifi-connections/native-audio.js#L263), but for Firefox the durations aren't as consistent and aren't as high. Is there another way we can detect if it's a stream? 

Opera still hasn't fixed the bug (reported in May), fwiw, so we'll probably have to find a workaround for Firefox too, which also gets me wondering… are we sure this isn't a problem with the streams we're testing?

**Comment by noslouch** [comment]
I think the streams are fine from what I can tell. NYPR’s streams are broadcast via Streamguys, who are pretty much the industry standard for such a thing at this point.

What I do know is that the browsers request data using different algorithms. Firefox will attempt to download an entire piece of audio in one go, whereas Chrome will download audio in “chunks”, using the Range header, expecting 216 response codes (partial content). 

I’m out of pocket at the moment, but you should be able to investigate the default behavior by popping one of the stream urls directly into the browser bar and watching the network tab. 

For more sophisticated debugging, we’ll sometimes use Charles to watch the raw network traffic, because the browser doesn’t always surface all kinds of requests.

**Comment by noslouch** [comment]
Also: Happy thanksgiving 🦃!

**Comment by jkeen** [comment]
Gobble gobble! 

Charles and the Network tab gave me no additional insight—I didn't see those 216s, nor did I discover some new magical way to determine a stream (yet). Although I did discover by mashing the refresh button that the problem in Firefox is ⚡️ INTERMITTENT ⚡️, in that occasionally it will report duration=Infinity correctly.

**Comment by jkeen** [comment]
Looks like this is fixed. Time fixes all wounds
