### ISSUE TITLE
How to set header to request to server

### ISSUE THREAD

**Issue by shcherbanikolay** [nypublicradio/ember-hifi#46]
Hello. I try to use your addon. It works grate from the local store. But i have trubles to play sound from server. My server demands auth header to be present. And the url looks like https://myserver.com/mailbox/greeting. When i send get request, the server return file that can be of mp3 or  wav. But i do not know the format before get it. That way i get warning about mime type. But if hifi service try to get record from server the conection refused because there is no auth header in request. How to add header to requests from adon? I do not anderstand what options i can set to play method. Or i need to download file to temp first and then play it from there. 

Thank you for your efforts to make this greate addon.

**Comment by noslouch** [comment]
Unfortunately, headers cannot be set on HTTP requests for assets loaded using an `Audio` element, which is what the `NativeAudio` connection uses for playback.

There may be a way to set headers using the `Howler` connection, because it uses XHR to load audio, but I'm afraid you'll need to dig into the [Howler docs](https://github.com/goldfire/howler.js/) to see if that's provided.

As an alternative, instead of protecting your audio assets behind and `Authorization` header, you could use cookies for auth. Browsers will always include cookies on HTTP requests to domains that have successfully set cookies on a previous request.
